### ISSUE TITLE
mmdetection2.1 Error

### ISSUE THREAD

**Issue by XcodeHw** [hkzhang95/DynamicRCNN#7] opened 2020-07-15 01:23 UTC
_base_ = '../faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
model = dict(
    roi_head=dict(
        type='DynamicRoIHead',
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=1,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))))
train_cfg = dict(
    rpn_proposal=dict(nms_thr=0.85),
    rcnn=dict(
        dynamic_rcnn=dict(
            iou_topk=75,
            beta_topk=10,
            update_iter_interval=100,
            initial_iou=0.4,
            initial_beta=1.0)))
test_cfg = dict(rpn=dict(nms_thr=0.85))

Traceback (most recent call last):
  File "train.py", line 153, in <module>
    main()
  File "train.py", line 149, in main
    meta=meta)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/esec/.local/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/esec/.local/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/esec/.local/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/detectors/base.py", line 236, in train_step
    losses = self(**data)
  File "/home/esec/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/detectors/two_stage.py", line 164, in forward_train
    **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/roi_heads/dynamic_roi_head.py", line 89, in forward_train
    img_metas)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/roi_heads/dynamic_roi_head.py", line 128, in _bbox_forward_train
    *bbox_targets)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 182, in loss
    reduction_override=reduction_override)
  File "/home/esec/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/losses/smooth_l1_loss.py", line 93, in forward
    **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/losses/utils.py", line 94, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home/esec/hewei/kaggle/mmdetection/mmdet/models/losses/smooth_l1_loss.py", line 21, in smooth_l1_loss
    assert beta > 0
AssertionError

**Comment by hkzhang95** [comment] 2020-07-17 10:19
This issue is weird. I implement Dynamic R-CNN using MMDetection V2.1 and make the pull request, then the reviewers merge the changes and successfully get correct results. Recently, I also try Dynamic R-CNN using [MMDetection V2.2.1](https://github.com/open-mmlab/mmdetection/tree/v2.2.1) and it works. I have some suggestions for you:

1. Try [MMDetection V2.2.1](https://github.com/open-mmlab/mmdetection/tree/v2.2.1)
2. Since MMDetection is a huge project and V2.1 contains a lot of commits, I need to know your detailed version (such as the commit id) to get more information and help you
3. From the error information, it seems like something is wrong with the recorded beta. So I have the following questions:
    - Are you using the official codebase without changing anything?
    - What is your dataset? COCO or other custom datasets?
    - Is this issue reproducible? Have you ever tried more than once and get different results?

**Comment by XcodeHw** [comment] 2020-07-20 02:45
my dataset ,coco style,only one class,try V2.2.1  ,same error

**Comment by hkzhang95** [comment] 2020-07-23 02:19
Considering that the error is `AssertionError` for `assert beta > 0`, I guess the new beta is 0 in some cases. In my implementation, beta is recorded as follows:

```
beta_topk = min(self.train_cfg.dynamic_rcnn.beta_topk * num_imgs, num_pos)
cur_target = torch.kthvalue(cur_target, beta_topk)[0].item()
self.beta_history.append(cur_target)
```

Since I have already taken the boundary check into account, maybe the error reason is that **there is no positive sample in the training procedure**. Note that the original Faster R-CNN will append the ground-truth bounding boxes into the batch when training. So does your dataset contains images with no object annotations and leads to this error?

**Comment by XcodeHw** [comment] 2020-07-23 05:09
i can train other networks successfully, and others have the same problem.https://github.com/open-mmlab/mmdetection/issues/3384

**Comment by hkzhang95** [comment] 2020-07-23 07:09
I re-consider this issue and comment on this [link](https://github.com/open-mmlab/mmdetection/issues/3384#issuecomment-662847364). Have a check on whether this explanation is helpful.

From my viewpoint, this is an extreme case that is not likely to occur on COCO dataset since there are a lot of positives in the training procedure. To handle these cases, maybe another restriction is required for beta such as adding a lower bound for the recorded values.

**Comment by XcodeHw** [comment] 2020-07-23 07:19
> I re-consider this issue and comment on this [link](https://github.com/open-mmlab/mmdetection/issues/3384#issuecomment-662847364). Have a check on whether this explanation is helpful.
> 
> From my viewpoint, this is an extreme case that is not likely to occur on COCO dataset since there are a lot of positives in the training procedure. To handle these cases, maybe another restriction is required for beta such as adding a lower bound for the recorded values.

ok ,thanks . i don't change np.median to np.mean, i can adjust  the beta_topk range ,for example ,beta_topk=10->beta_topk=50,it works ,you are right , maybe another restriction is required for beta .

**Comment by hkzhang95** [comment] 2020-07-23 07:35
Good job. I will close this issue now. You can re-open it if you have new questions.

**Closed as completed by hkzhang95** 2020-07-23 07:35 UTC
